# ~/.config/starship.toml

# Use custom format
# format = """
# [ ┌─{ ](bold white)$directory$git_branch
# [ └────<$character>─{](bold white) """

format = """
 $directory$git_branch
 $character """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[character]
# success_symbol = "[o](bold cyan)"
# error_symbol = "[o](bold red)"
success_symbol = "[>](bold cyan)"
error_symbol = "[>](bold red)"
format = "$symbol"

[directory]
truncation_symbol = "···/"
